// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered style recommendations based on user preferences and browsing history.
 *
 * - getStyleRecommendation - A function that returns a style recommendation.
 * - StyleRecommendationInput - The input type for the getStyleRecommendation function.
 * - StyleRecommendationOutput - The return type for the getStyleRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleRecommendationInputSchema = z.object({
  userPreferences: z
    .string()
    .describe(
      'A description of the users style preferences including brands, colors and styles.'
    ),
  browsingHistory: z
    .string()
    .describe(
      'A description of the users browsing history, including types of shoes viewed, brands, and specific product names.'
    ),
});
export type StyleRecommendationInput = z.infer<typeof StyleRecommendationInputSchema>;

const StyleRecommendationOutputSchema = z.object({
  styleRecommendation: z
    .string()
    .describe(
      'A style recommendation based on the users provided preferences and browsing history. Provide the shoe style.'
    ),
  reasoning: z
    .string()
    .describe(
      'The reasoning behind the recommendation, referencing the user preferences and browsing history.'
    ),
});
export type StyleRecommendationOutput = z.infer<typeof StyleRecommendationOutputSchema>;

export async function getStyleRecommendation(
  input: StyleRecommendationInput
): Promise<StyleRecommendationOutput> {
  return styleRecommendationFlow(input);
}

const styleRecommendationPrompt = ai.definePrompt({
  name: 'styleRecommendationPrompt',
  input: {schema: StyleRecommendationInputSchema},
  output: {schema: StyleRecommendationOutputSchema},
  prompt: `You are a personal style assistant for shoes. Your goal is to recommend a style of shoe that a user will enjoy based on their preferences and browsing history.

  User Preferences: {{{userPreferences}}}
  Browsing History: {{{browsingHistory}}}

  Based on these preferences and browsing history, what style of shoe would you recommend and why?
  Ensure that the styleRecommendation field only contains the style of shoe and the reasoning field explains the choice.
  `,
});

const styleRecommendationFlow = ai.defineFlow(
  {
    name: 'styleRecommendationFlow',
    inputSchema: StyleRecommendationInputSchema,
    outputSchema: StyleRecommendationOutputSchema,
  },
  async input => {
    const {output} = await styleRecommendationPrompt(input);
    return output!;
  }
);
